[package]
name = "diluvio-net"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.25.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
zip = "0.5"